# Generated by Django 2.2.5 on 2019-09-02 12:30

from django.db import migrations, models
import oauth2client.contrib.django_util.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=128)),
                ('credentials', oauth2client.contrib.django_util.models.CredentialsField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
